#theme: jekyll-theme-tactile
#theme: default

defaults:
  -
    scope:
        path: "" # an empty string here means all files in the project
    values:
        postsPageUrl: "posts"
        excerpt_separator: <!--more-->
        layout: "default"
        siteTitle: "Beer Caps Collection"
        copyright: "&copy; 2021 AB Labs"
