openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Lots API'
  description: Azure Lots API endpoints list
servers:
    - description: Development environment
      url: https://devapim.christies.com/dev/lots
    - description: Test environment
      url: https://devapim.christies.com/test/lots
    - description: Integration environment
      url: https://devapim.christies.com/sit/lots
    - description: Acceptance environment
      url: https://devapim.christies.com/uat/lots
    - description: Hotfix environment
      url: https://apim.christies.com/lots
    - description: Production environment
      url: https://apim.christies.com/lots
paths:
  /:
    get:
      summary: 'Returns lots collection filteres by the query parameters'
      parameters:
          - $ref: '#/components/parameters/ids'
          - $ref: '#/components/parameters/language'
      responses:
        '200':
          description: 'OK'
          content:
            application/vnd.christies.v1+json:
              schema:
                $ref: '#/components/schemas/Lots'
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "403":
          $ref: "#/components/responses/Forbidden"
components:
  parameters:
    language:
        in: query
        name: language
        schema:
            type: string
            example: "en"
            enum: ["en", "zh-hans", "zh-hant", ""]
    ids:
        in: query
        name: ids
        example: "1,2,3"
        schema:
            type: string
  schemas:
    Lots:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  responses: 
    BadRequest:
      description: 'Invalid query parameters provided'
    Forbidden: 
      description: 'The number of ids exeeded the limit'
    Unauthorized: 
      description: 'User must be authenticated to make a call'
   